/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.uis.organizationapp.cronometro;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import co.edu.uis.organizationapp.modelo.Usuario;
import co.edu.uis.organizationapp.modelo.UsuarioManager;
import javax.swing.JOptionPane;
/**
 *
 * @author Karol Hernandez
 */
public class Cronometro extends javax.swing.JFrame {

    /**
     * Creates new form Cronometro
     */
    private Thread cronometroThread;
    private volatile boolean corriendo = false;
    private volatile boolean pausado = false;
    private long startTime = 0L;
    private long tiempoAcumulado = 0L;
    private Usuario usuario;
    private long ultimosPuntosOtorgados = 0L;
    private static final int SEGUNDOS_PARA_PUNTO = 600; // 10 minutos
    private static final int PUNTOS_POR_BLOQUE = 10;
    private javax.swing.JLabel lblPuntos;

    public Cronometro() {
        initComponents();
        usuario = UsuarioManager.cargarUsuario();
        actualizarLabel(0);
        actualizarPuntosUI();
        btnPause.setEnabled(false);
        btnStop.setEnabled(false);
        setTitle("Cronómetro - Puntos: " + usuario.getPuntos());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCronometre = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnPause = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        lblPuntos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblCronometre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCronometre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCronometre.setText("00:00:00:00");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Cronómetro");

        lblPuntos.setFont(new java.awt.Font("Segoe UI", 0, 18));
        lblPuntos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPuntos.setText("Puntos: 0");
        lblPuntos.setForeground(new java.awt.Color(0, 120, 212));

        btnPause.setText("Pausar");
        btnPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPauseActionPerformed(evt);
            }
        });

        btnStart.setText("Iniciar");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnStop.setText("Detener");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCronometre, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnStart)
                        .addGap(18, 18, 18)
                        .addComponent(btnPause)
                        .addGap(18, 18, 18)
                        .addComponent(btnStop)
                        .addGap(19, 19, 19))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addGap(10, 10, 10)
                .addComponent(lblPuntos)
                .addGap(8, 8, 8)
                .addComponent(lblCronometre)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPause)
                    .addComponent(btnStop)
                    .addComponent(btnStart))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarCronometro() {
        if (cronometroThread != null && cronometroThread.isAlive()) {
            tiempoAcumulado = 0L;
            startTime = System.nanoTime();
            pausado = false;
            corriendo = true;
            ultimosPuntosOtorgados = 0L;
            return;
        }
        corriendo = true;
        pausado = false;
        tiempoAcumulado = 0L;
        startTime = System.nanoTime();
        ultimosPuntosOtorgados = 0L;
        cronometroThread = new Thread(() -> {
            while (corriendo) {
                if (!pausado) {
                    long tiempoTranscurrido = tiempoAcumulado + (System.nanoTime() - startTime);
                    javax.swing.SwingUtilities.invokeLater(() -> actualizarLabel(tiempoTranscurrido));
                    otorgarPuntosSiCorresponde(tiempoTranscurrido);
                }
                try {
                    Thread.sleep(10);
                } catch (InterruptedException e) {
                    break;
                }
            }
        });
        cronometroThread.start();
    }

    private void otorgarPuntosSiCorresponde(long nanos) {
        long totalSeconds = nanos / 1_000_000_000L;
        long bloques = totalSeconds / SEGUNDOS_PARA_PUNTO;
        if (bloques > ultimosPuntosOtorgados) {
            usuario.sumarPuntos(PUNTOS_POR_BLOQUE);
            UsuarioManager.guardarUsuario(usuario);
            ultimosPuntosOtorgados = bloques;
            setTitle("Cronómetro - Puntos: " + usuario.getPuntos());
            actualizarPuntosUI();
            animarPuntosGanados();
            JOptionPane.showMessageDialog(this, "¡Felicidades! Has ganado " + PUNTOS_POR_BLOQUE + " puntos por estudiar 10 minutos.", "Puntos otorgados", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void pausarCronometro() {
        pausado = true;
        tiempoAcumulado += (System.nanoTime() - startTime);
    }

    private void reanudarCronometro() {
        pausado = false;
        startTime = System.nanoTime();
    }

    private void detenerCronometro() {
        corriendo = false;
        pausado = false;
        if (cronometroThread != null) {
            cronometroThread.interrupt();
        }
        tiempoAcumulado = 0L;
        ultimosPuntosOtorgados = 0L;
        actualizarLabel(0);
    }

    private void actualizarLabel(long nanos) {
        long totalCentis = nanos / 10_000_000L;
        long cs = totalCentis % 100;
        long totalSeconds = totalCentis / 100;
        long s = totalSeconds % 60;
        long totalMinutes = totalSeconds / 60;
        long m = totalMinutes % 60;
        long h = totalMinutes / 60;
        String Tiempo = String.format("%02d:%02d:%02d:%02d", h, m, s, cs);
        lblCronometre.setText(Tiempo);
    }

    private void actualizarPuntosUI() {
        lblPuntos.setText("Puntos: " + usuario.getPuntos());
    }

    private void animarPuntosGanados() {
        java.awt.Color original = lblPuntos.getForeground();
        lblPuntos.setForeground(new java.awt.Color(0, 180, 0));
        new Thread(() -> {
            try {
                Thread.sleep(800);
            } catch (InterruptedException ignored) {}
            javax.swing.SwingUtilities.invokeLater(() -> lblPuntos.setForeground(original));
        }).start();
    }

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        if (!corriendo) {
            iniciarCronometro();
            btnStart.setText("Reiniciar");
        } else {
            tiempoAcumulado = 0L;
            startTime = System.nanoTime();
            actualizarLabel(0);
            reanudarCronometro();
        }
        btnStart.setEnabled(false);
        btnPause.setEnabled(true);
        btnStop.setEnabled(true);
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        detenerCronometro();
        btnStart.setEnabled(true);
        btnStart.setText("Iniciar");
        btnPause.setEnabled(false);
        btnStop.setEnabled(false);
    }//GEN-LAST:event_btnStopActionPerformed

    private void btnPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPauseActionPerformed
        pausarCronometro();
        btnStart.setEnabled(true);
        btnPause.setEnabled(false);
    }//GEN-LAST:event_btnPauseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPause;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCronometre;
    // End of variables declaration//GEN-END:variables
}
